#!/usr/bin/env python3
"""Check build/import-public-build.py over a small synthetic fixture.

The importer's real input lives outside this repo, so this test feeds it a fixture with one
provenance comment, one Google Fonts link and one SES CDN import (plus the worker prelude head
it also rewrites), and asserts all of them are replaced; then, for each of the three, a fixture
missing it must make the importer exit non-zero. The importer writes next to itself
(build/input/), so it runs from a copy in a temporary folder and the committed input is untouched.
"""
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMPORTER = ROOT / "build" / "import-public-build.py"

PROVENANCE = "<!-- Public read-only copy of https://example.com/original-game. Do not edit this file: edit the original and rebuild. -->\n"
FONTS = '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap">'
SES = "importScripts('https://cdn.jsdelivr.net/npm/ses@2.3.0/dist/ses.umd.min.js')"
PRELUDE = 'const SES_PRELUDE = "var SES_STATE = \'off: not loaded\'; try { ' + SES + '; lockdown(); SES_STATE = \'on\'; } catch (e) {}";\n'


def fixture(provenance=True, fonts=True, ses=True):
    return ("<!doctype html><html><head>\n"
            + (PROVENANCE if provenance else "")
            + "<title>fixture</title>\n"
            + (FONTS if fonts else '<link rel="stylesheet" href="local.css">') + "\n"
            + "</head><body><script>\n"
            + (PRELUDE if ses else 'const SES_PRELUDE = "var SES_STATE = \'off: not loaded\';";\n')
            + "</script></body></html>\n")


def run(tmp, text):
    src = tmp / "public-build.html"
    src.write_text(text, encoding="utf-8")
    out = tmp / "build" / "input" / "game-public.html"
    if out.exists():
        out.unlink()
    p = subprocess.run([sys.executable, str(tmp / "build" / "import-public-build.py"), str(src)],
                       capture_output=True, text=True, check=False)
    return p, (out.read_text(encoding="utf-8") if out.exists() else None)


def main():
    failures = []
    with tempfile.TemporaryDirectory() as d:
        tmp = Path(d)
        (tmp / "build").mkdir()
        shutil.copy(IMPORTER, tmp / "build" / "import-public-build.py")

        p, out = run(tmp, fixture())
        if p.returncode != 0 or out is None:
            failures.append(f"the full fixture did not import (exit {p.returncode}): {p.stdout}{p.stderr}")
        else:
            for bad, what in (("Public read-only copy of", "provenance comment"), ("fonts.googleapis.com", "Google Fonts link"),
                              ("cdn.jsdelivr.net", "SES CDN import")):
                if bad in out:
                    failures.append(f"the {what} is still in the output")
            for good, what in (('<link rel="stylesheet" href="fonts/fonts.css">', "local fonts link"), ("importScripts(SES_URL)", "local SES import"),
                               ("var SES_URL = ", "SES_URL in the worker prelude")):
                if out.count(good) != 1:
                    failures.append(f"the {what} appears {out.count(good)} times, want 1")

        for missing in ("provenance", "fonts", "ses"):
            p, out = run(tmp, fixture(**{missing: False}))
            if p.returncode == 0:
                failures.append(f"a fixture without its {missing} edit point imported with exit 0")
            if out is not None:
                failures.append(f"a fixture without its {missing} edit point still wrote an output")

    if failures:
        print("FAILED import-check\n  " + "\n  ".join(failures))
        sys.exit(1)
    print("OK import-check")


if __name__ == "__main__":
    main()
